### ISSUE TITLE
Make "Submit for Approval" timeline button clickable to open modal window

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-application#113]

**Comment by tbeck** [comment]
Will be updated as part of #125

**Comment by paulstroot** [comment]
With the refactor of the form, you can now click any item in the timeline that has been marked as "complete" to allow you to jump forward or backwards in the timeline. The "Submit for approval" button appears at the bottom of the "Review" page. Please let me know if you're happy with this setup.

**Comment by ZiggyAtl** [comment]
@paulstroot I think the way you've created it is great. However as I mentioned in a previous issue, whenever the user clicks the Save Changes button, the green Product Updated message comes up and then the page just reverts back to what it was like before the changes were entered.

**Comment by paulstroot** [comment]
Since this issue is related to making the "Submit for approval" button clickable. (and we removed that button in the timeline and placed the button on the "Review" page. 

I will open a new issue for  "Product data not saving properly."

**Comment by paulstroot** [comment]
Noticed that we already have an issue for this. Removing the new #143 Issue I created, and flagging this as a duplicate of issue #112
