### ISSUE TITLE
DAB custom price selector - Add Alt to delete instructions

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-application#115]
When selecting the various DABs which fall in to each pricing tier, I realize if I am selecting multiple ones I have to hold the shift key down (unless I'm dragging through them). However if I have already selected a group from one tier, then go to select some in another tier, then go back and select some more to allocate to the original tier, all the original ones I selected disappear unless I hold the shift key down. 

1) It would be better if those original ones which were assigned are maintained in it's memory, without the user having to remember to hold the shift key down again.

2) The button underneath the prices on the on the custom pricing screen says 'Submit' but this is confusing as there is another further above which says 'Submit for Approval' so I was concerned it was going to submit for approval rather than just saving those pricing changes. Please can you therefore change the button at the bottom to 'Save Changes'. Added to which would it be better if the View Details and Submit for Approval buttons weren't on this page, and only reappeared once the user saved pricing changes and it took them back to the previous page?

**Comment by paulstroot** [comment]
Regarding the first issue, let me clarify to make sure I understand.

Currently, when selecting DABs to assign to a pricing tier. Not holding down any key will replace the selection with what is clicked, holding the "shift" key will add the selected DABs to what was previously clicked, and holding down the "alt"
 key will remove any previously selected tiles. (This functionality was taken from most image editing programs in the hops that the key commands might be familiar to users)
 
What you are suggesting is that the default behavior, without holding down any key, would be to add the selected tiles to what was previously selected. We would still have the "alt" key behavior to remove selected tiles. And there would be no functionality to replace all selected tiles. (The user would probably need to hold the "alt" key and drag across the entire image to remove all previously selected tiles.

Am I understanding this correctly.

**Comment by ZiggyAtl** [comment]
@paulstroot that would definitely achieve what I'm looking for, yes. I think the problem is that people would select a few for a price tier, and then maybe select some more as they looked at it, or maybe came back to it later to add some more. Or maybe have a stab at it and then show someone else for approval. As it is now, if they one time forgot to hold the shift key, they'd lose everything they'd already selected. 

And then having the alt key to remove, either single tiles or alt/dragging across a number of them would work to deselect any they decided they didn't want, or wanted to assign to another tier.

**Comment by ZiggyAtl** [comment]
@paulstroot I went to an artwork page to test this (The Persistence of Memory). I created a new price tier, however the system wouldn't let me assign anything to the painting, whether I clicked on individual tiles or dragged through them all.

**Comment by paulstroot** [comment]
@ZiggyAtl , Try this again now and let me know if you're still getting the same results.

**Comment by ZiggyAtl** [comment]
@paulstroot I am unable to test this as neither of the two artworks in the system will allow me to edit them, as there is no edit feature showing any more

**Comment by ZiggyAtl** [comment]
@paulstroot it will now let me drag through multiple selections. It would be useful if you could add a note for people to use the alt key if they want to deselect a higher tier on a tile and just revert it back to level 1. I spent a while getting frustrated that I couldn't select tier 1 as a pricing option to convert some of the tiles back to a tier 1

**Comment by paulstroot** [comment]
Thanks. That was in there previously but it must have gotten lost in the refactor. I will add it back in shortly.

**Comment by paulstroot** [comment]
I added some instructions both under the variant fields:
`Select a pricing tier, then select tiles on the image to add them to the tier. Drag to select multiple tiles. Alt+click to remove tiles.`

And also when you hover over the artwork
