### ISSUE TITLE
Refactor Create/Edit art form 

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-application#125]
Make it a multi-step Formik form, with the Dab-selector as a child component with multiple states.

**Comment by paulstroot** [comment]
Updates have been pushed. Check it out here.
https://comission-application.web.app/

**Comment by ZiggyAtl** [comment]
@paulstroot same comment here as I've left on the others. Unfortunately was unable to check as I can't access the price tier info in the sample artworks which are on the site, and none of the info was able to be edited as the edit function no longer appears.

**Comment by ZiggyAtl** [comment]
@paulstroot does this still need to be left open, taking in to account the comments I've made on #113 and #116. Or because the are still open could this one be closed?

**Comment by paulstroot** [comment]
I think we can close this issue, since the refactor has been pushed for QA, and address bugs with the form in different issues.
