### ISSUE TITLE
Text change to artwork statuses

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-application#126]
I want to create the perception that once they upload the artwork and enter the details, all the magic is done after they submit for approval. Therefore please can you substitute the word 'CoMissioning' instead of 'Approval'. Therefore the buttons would say 
Submit for CoMissioning
Awaiting CoMissioning

And please use Fractionalize instead of Fractalize, and Fractionalized instead of Fractalized

**Comment by ZiggyAtl** [comment]
@paulstroot I clicked Submit for Commissioning button on the Venice at Sunset page and that status appears on the individual artwork page, however on the main Manage Art page it hasn't updated and still says In Progress

**Comment by paulstroot** [comment]
I created a new issue for this Bill. If the text on the buttons looks okay you can close the issue.

**Comment by ZiggyAtl** [comment]
@paulstroot good morning Paul. Yes text looks OK thanks
