### ISSUE TITLE
Changes still possible after being sent to CoM

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-application#127]
After an artwork has been sent for approval (CoMissioning) it says 'Closed for editing' on the page. However if you click on the View Details button, there is a link which says Re-fractalize Image (should say Refractionalize) and if you click on the link you can change the number of dabs and the membership period. This also applies for the artworks which have been approved and gone live.

There is also a link to Release All unavailable DABs which is still active.

Shouldn't those links be removed at that stage so they can't change it?

**Comment by paulstroot** [comment]
This will be updated along with the form refactor I'm working on #125

**Comment by paulstroot** [comment]
Updates made. If the art has been submitted for CoMissioning, the user should skip any of the input forms and go straight to a page that displays details about their art, with no editing capabilities.

**Comment by ZiggyAtl** [comment]
@paulstroot am unable to test this as neither of the two sample artworks in the system are at the "Sent for CoMissioning' stage. Please can you add one so I can see what this looks like
