### ISSUE TITLE
Assigning pricing layers

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-application#128]
On the page where you can assign dabs to other pricing tiers, is it possible to have an undo button and/or a save changes button? The problem with the system is that if someone does something wrong they can lose everything they've already assigned, and then they have to start all over again. If they've got a painting which is thousands of DABs, that would be a pain

**Comment by paulstroot** [comment]
New refactor of this form will include a "save" button in the top right corner. This will allow the user to save at any point in the process. (note: at this time, (friday 11/4), the save button is not fully functional, but it is in place and mostly working for editing existing art.

**Comment by ZiggyAtl** [comment]
Thanks for the update @paulstroot . Do you want to close this out now, or wait until the work is complete?

**Comment by paulstroot** [comment]
I've updated the multi-step form for creating and editing art. I'm going to close this issue because the "Save" button has been added. If you have any comments about the placement or functionality of the button you can open a new issue.
