### ISSUE TITLE
Editing Museum Info page

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-application#130]
When the screen is in the edit mode it won't allow the Museum Overview text to be edited.

Please can you change the blue button at the bottom from Submit to Save Changes. Would it also be an idea to also have the same button at the top of the page too, beside the Edit button?

**Comment by paulstroot** [comment]
Update made. there is now a "save" button at the top of the form. The final button of the multi-step form will say "Submit for CoMissioning"

**Comment by ZiggyAtl** [comment]
@paulstroot I have tried clicking the Edit button a few times on the Museum Info page so I can test the above, and it just goes to a white screen (I'm using safari)

**Comment by paulstroot** [comment]
Sorry, I was neck deep in some other changes and I must have broken that edit form while I was working on it. It should be ready for review now.

(Note that my last comment I had misudnerstood the request, and I mentioned a save button that I was adding to the "create/edit" art form, not the Museum edit form.)
