### ISSUE TITLE
Add Art section

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-application#131]
- [x] When I clicked on the Add Art button and went to the page it already had some information in some of the boxes. Please can it be removed, apart from the description in the Purchase Support Note.
- [x] In the blue ? info button on the Artist section please use the text; Select from the CoMission artists in the drop down. To have a new artist added please contact support@comission.art

- [x] In the ? info button on the copyright section, please can you modify the wording to say "Please enter copyright information in the following format: Copyright [YEAR] [HOLDER NAME]
- [x] The Base Price only allows me to go to 999.99. It's highly unlikely a base price will ever be +$1000, but is it easy enough to make that field accept higher numbers so we have the option?
- [x] Can the ? info button for the Base Price say: The default price for all Digital Art Blocks before any additional price tiers are added
- [x] The Artwork Description box doesn't allow me to enter anything in there. That also prevented me submitting the art as it's a required field. It also has the text formatting tools in there which I assume is wrong, as we want this text to be the same format as everything else?  
- [x] Please can the text in the Purchase Support Note box be "The funds from this DAB purchase......" and can the ? info button remind them of the max characters
- [x] When I added another line to the Provenance, the message in red appeared (screenshot)
![Screen Shot 2022-11-02 at 11 43 54 AM](https://user-images.githubusercontent.com/112654923/199535330-c84a5cee-e3a2-4f15-bb59-7223cd653585.png)

**Comment by ZiggyAtl** [comment]
@paulstroot Its really taking shape and what you've added will significantly improve the UI. Thank you. Couple of things I've found...

- [ ] In Add Art the description section still has text formatting tools
- [ ] The sample text in the copyright box needs updating to “i.e. Copyright 2022 Pablo Picasso 
- [ ] On the second page its missing the word 'the' in between create and digital
- [ ] Before filling in any data I realized I hadn't saved anything from the previous page so I hit Save Changes and got these error messages displayed
![Screen Shot 2022-11-04 at 5 47 28 PM](https://user-images.githubusercontent.com/112654923/200081829-8387681b-175b-4712-8798-d127443f007b.png)

- [ ] Then I hit the back button on the browser and got this error message, which probably referred to the previous page as there was nothing to correct on the first page.
![Screen Shot 2022-11-04 at 5 48 30 PM](https://user-images.githubusercontent.com/112654923/200081883-b638865d-aa8e-4700-9d07-87db45b8c6a3.png)

- [ ] Then after I had entered all the pricing tier info and hit next to move to the next page I got the white screen. I tried refreshing and it took me back to the very beginning, with no information saved apart from the Purchase Support Note

- [ ] I then tried entering all the information again, but the Next button was greyed out, even though everything was entered.

**Comment by paulstroot** [comment]
Hi Bill. Sorry about all the errors you got. I probably should have let you know that I was still working on the functionality of being able to navigate the form and save as you go. The few updates I had marked as ready for review I think were just to indicate that that individual item had been updated, but the whole form was not working yet.

That said, I just uploaded an update and I think it is mostly working. I'll be catching more bugs today, but If you want to check out the items in this task you can try it again.

**Comment by paulstroot** [comment]
@ZiggyAtl , I have either checked things off, or created new issues for some of the remaining items here.

**Comment by ZiggyAtl** [comment]
@paulstroot I'm trying to check the Add Art section however the fault we had previously where I can't select the Description box and enter any text has returned, so it therefore won't let me move ahead in the process

**Comment by paulstroot** [comment]
Hmmm. I've tried this on Chrome and Safari on mac, and chrome on PC and I'm not able to recreate it. To clarify, is that problem that you can place your cursor in the Description field on the first page of the form, but whey you try to type no characters appear in the form?

**Comment by ZiggyAtl** [comment]
@paulstroot I tried it on Safari and Chrome on my Mac and it doesn't work on either. I even cleared my history / cookies in safari just in case. Added a screen shot below. I can enter the cursor in all the other boxes and type information. But it won't let me click anywhere in the description box (like its greyed out)
![Screen Shot 2022-11-07 at 2 01 38 PM](https://user-images.githubusercontent.com/112654923/200393651-61b94f8f-bed6-41d5-bde6-5033122395fd.png)

**Comment by ZiggyAtl** [comment]
@paulstroot made a mistake in my comment above. The problem is just safari, it works on chrome (which is why I cleared everything in safari and tried again)

**Comment by paulstroot** [comment]
Thanks for the details Bill. For now I have made the description box not required so you'll be able to at least make it past this first page.

Both Tom and I have not had any issues getting this working on Safari. Perhaps we can screen share with you sometime this week so we can walk through the steps you're seeing to try to troubleshoot.

**Comment by ZiggyAtl** [comment]
@paulstroot absolutely. Happy to jump on a call with you tomorrow to do this. I can be pretty flexible if you want to give me a couple of times that suit you two.
