### ISSUE TITLE
Editing the description not working 

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-application#147]
From Bill:

...tried it on Safari and Chrome on my Mac and it doesn't work on either [correction - it works in chrome, not safari]. I even cleared my history / cookies in safari just in case. Added a screen shot below. I can enter the cursor in all the other boxes and type information. But it won't let me click anywhere in the description box (like its greyed out)

**Comment by ZiggyAtl** [comment]
@paulstroot  strange but in the last hour I clicked on the Add Art to review everything and it let me enter text in the description. I just went back in to try again and it won't let me do that

**Comment by paulstroot** [comment]
You should be able to proceed without entering anything in the description field, correct? We can walk through the error's your having with this when we meet on Thursday, or earlier if you'd like to schedule a call.

**Comment by ZiggyAtl** [comment]
@paulstroot Tried now and everything seems to be working with that description box so I'll mark it as closed

**Comment by ZiggyAtl** [comment]
@paulstroot I spoke too soon. I just went back in to load another piece of art (using same artwork as before) and now unable to enter anything in the Description box

**Comment by paulstroot** [comment]
Hi @ZiggyAtl. If you are encountering this issue with the description field tomorrow during the day, would you be available for a quick video call so I can see your screen as you're getting the error?

**Comment by ZiggyAtl** [comment]
@paulstroot yes, I am available from 11:30-1:30pm EST

**Comment by paulstroot** [comment]
Hi @ZiggyAtl . I am unfortunately not available in that timeslot but @tbeck is and he can connect with you to try to get this details form field issue figured out. He just set up a calendar event and invited you. Let us know if you see this notification late.

**Comment by paulstroot** [comment]
Hi @ZiggyAtl, from what I gathered from Tom, it sounds like the issue is sporadic. I have been doing a lot of active development the last couple of days so perhaps the script was throwing an error when you clicked in the description field. Let's keep this issue open for a few days, and if you run into it again please let us know so we can help troubleshoot.

**Comment by ZiggyAtl** [comment]
@paulstroot I've tested this a number of times now, and not seen the fault reappear, so hopefully it's now resolved. Should we revert back to making it a required field now?
