### ISSUE TITLE
Delete this art button

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-application#153]
@paulstroot Thank you for the new 'Delete This Product' button. It is in the right place on the Fractionalize and Membership pages, but moves around on the others. On one page it is right at the bottom of the page and couldn't be seen unless the user scrolls right down.

**Comment by paulstroot** [comment]
I have it placed below all other content, on the left side of the screen. I think it's perfectly fine if this appears "below the fold", since it is a button that should rarely be used. What are your expectations about where it should be placed?

**Comment by ZiggyAtl** [comment]
@paulstroot I agree with you that it would be better at the bottom of the page, so that it doesn't accidentally get used. I just pointed it out because it appeared there on some items, but directly under the some of the other buttons in others, so was just looking for some consistency. Looks like the update you did has dealt with that. Cheers
