### ISSUE TITLE
Archive function not updating in the app

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-application#154]
@paulstroot I tried out the archive function in shopify, as we will need to use that moving forward when we want to take something off the museum app's art management function, and not the delete function (which loses the history of everything). 

When I click on it the following message comes up, which makes sense;
Archiving this product will hide it from your sales channels and Shopify admin. You’ll find it using the status filter in your product list.

The only thing is it doesn't then update in the app. It leaves the art there, with whatever status it was at, and even allows the museum to continue to process it and add/update details.

**Comment by paulstroot** [comment]
Updated made. Please review.

**Comment by ZiggyAtl** [comment]
@paulstroot thanks for this. Couple of things

- [ ] When it's archived, it's like the CoMissioning process in that the museum app doesn't update and you have to refresh the screen to see the update.
- [ ] When it's archived, its greyed out on the manage art page and shows as archived (which is good). However it still allows the user to access the artwork page, and then all the detail is editable, the submit for CoMissioning button is active (as if it was still in the In Progress' stage)
- [ ] Once it's unarchived it reverts back to Draft status, even if it had previously been at CoMission'ed stage. Can it not revert back to the status it was when it was archived?

**Comment by ZiggyAtl** [comment]
@paulstroot hi Paul I just checked that and it seems to be working how you described. I had hoped you were going to address it by keeping it as greyed out, and removing the ability for people to edit anything after it had been archived. That way the info was still available to the museum. But if that is the only way to address the issue I'm OK with that.

**Comment by paulstroot** [comment]
I updated this for you @ZiggyAtl so that archived items are greyed out and not clickable.

**Comment by ZiggyAtl** [comment]
Great, thank you
