### ISSUE TITLE
Update Shopify Integration

### ISSUE THREAD

**Issue by tbeck** [ocupop/comission-application#202]
**Describe the task that you'd like to track**

We have gotten notice through the Shopify Partner Portal that updates may potentially be required that are relevant to this application: 

https://gyazo.com/1d3c815fa7caa4900ae01140fe7b2cac 

@paulstroot - Can you research a little and determine if any updates are required?

Here is a direct link referenced in the notification: https://shopify.dev/docs/apps/fulfillment

**Comment by paulstroot** [comment]
I looked into this and we are okay on the comission front. The migration is for making sure all "Fulfillment" abnd "Order" API Calls are migated to the newer "FulfillmentOrder" call (for both Rest API and GraphQL). We are already using the newer method for comission.
