### ISSUE TITLE
Custom order notification

### ISSUE THREAD

**Issue by tbeck** [ocupop/comission-application#85]
We need to be able to include collection (Museum) metafield values in the order confirmation email. Specifically, @ZiggyAtl  would like order confirmations to include tax details associated with the 501c non-profit statements.

Since Shopify does not have a mechanism for including collection(Museum) details in email templates we are looking into other methods to accomplish this.

1. Create a transactional email service on the Firebase platform that takes the webhook data posted by an order complete event to create these custom notifications.
2. Retain some content management capabilities offered by Shopify to allow @ZiggyAtl to adjust the other language and content in these emails.

@paulstroot - feel free to add any additional details I missed.

**Comment by ZiggyAtl** [comment]
I think what we're needing to do might be a lot easier than this. All the info needed is already contained within our system
1) Name of the organization (museum name). Their official name may be slightly different to their DBA name, so could we just have a box in the museum set up section which lists their official name, and the receipt which goes out could just capture that?
2) The amount of the donation (the price of the DAB)
3) A statement that no goods or services were provided by the organization in return for the contribution (which will be the case for the MVP).
4) A description and good faith estimate of the value of goods and services, if any, that an organization provided in return for the contribution (which would be the case for v2).

**Comment by tbeck** [comment]
https://github.com/ocupop/comission-shopify-hydrogen/issues/60
