### ISSUE TITLE
Change label "Note" to something more descriptive (Bill will get back to us on this)

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-application#90]

**Comment by paulstroot** [comment]
We have a field for artwork labeled "Note". This appears in three places: 

1. On the artwork details page
2. In the certificate
3. In the confirmation email to the user after a purchase

Is it okay to use this same copy for all three locations, or do we need to break it up (i.e., the certificate copy will need a character limit, the confirmation copy may need to include some tax exception text, etc.)

We may want to change the label for this field in the museum admin to be more descriptive of what it is. Additionally, we can have some hint text in the form for adding new art to help explain this. We need to come up with this label and hint text.

**Comment by ZiggyAtl** [comment]
@paulstroot can you tell me where this text currently originates from please (who enters it and where)? If you don't know, maybe Jenny does. From memory we added a box which then used this text on the various locations

**Comment by alexjlahr** [comment]
Hey @paulstroot — I think the [Museum Application copy doc](https://docs.google.com/document/d/1Q8xhfew_fgxFH9mkn5OZBzkkuZ56Vc1-es0UVzo-n7Q/edit) I shared might have some direction in this area. I know it's not the most organized, so let me know how else I can help to provide better context.

Also, what is our character limit for the Certificate? Perhaps we reveal that within the Add Artwork flow within the Museum Application to alleviate any issues.

**Comment by paulstroot** [comment]
This text is set in the Museum Application when a museum admin creates a new Art entry.

I'm working on implementing the design now, which will let me know what our maximum character count is. For the certificate, it's looking like around 200 characters.

**Comment by ZiggyAtl** [comment]
@paulstroot  For the new art entry created by the admin that you refer to above, 200 characters is perfect. And we want it displaying on the artwork website page and on the certificate. You're right about it needing a different label and hint text, which I will send through. Before I do that please can you send me a screen shot of what that page looks like, or send me a link so I can access it. I want to make sure any text I give you is also in context with the other boxes around it.

I can't remember seeing where it appears in the confirmation email after purchase. Please can you resend me a copy of that email so I can check it.

We definitely need some text on the confirmation email other than this, which gives the official organization name and tax info. Would the easiest way to achieve this be to add another box in the museum admin area for the museum to enter this, and then have that appear on the email confirmation?

**Comment by paulstroot** [comment]
Here is where that text shows up on the product detail page.
![image](https://user-images.githubusercontent.com/52838369/196469561-937f5163-352c-4bf4-9e83-57d0758ddd09.png)

And in the certificate:
![image](https://user-images.githubusercontent.com/52838369/196469948-89d402d1-5753-442d-9626-00a343e04f1c.png)

For the confirmation email, you're right, it's not currently in there. We had talked about putting it in the email at one point. I believe we now are talking about sending a second email with information about tax deductible donations. We could place some custom text in that email. or perhaps that email can be generated entirely with the info that we currently have (Corporate name, tax ID, address, etc)

I think if we have different needs for these different areas where the text displays, then yes, it probably would be best to create separate inputs for each area.

**Comment by ZiggyAtl** [comment]
@paulstroot sorry I meant please could you send me a screen shot for the museum admin data entry page

**Comment by ZiggyAtl** [comment]
@paulstroot below is the ideal wording which describes to the user what the note is, and some sample wording to go in the box. However, is it possible to include something like this or is it too long, and does it need just a title, rather than something descriptive?

TAB NOTE
Write a description of how the funds from the DAB purchase are going to be used, using a max of 200 characters (incl spaces). This will appear on the website and also on the certificate the purchaser receives. You can be as non specific as you want e.g. helping us with our operating costs. However remember that our audience is inspired by supporting a cause. The more specific you can be with this, the more likely they will be to feel connected to what you’re doing, and therefore more likely to support it.

SAMPLE WORDING 
The proceeds from your purchase will help fund the Beath Museum's Caterpillar art program. The program provides free art classes and access to materials to children aged 5-11 yrs old from a number of under served communities in our City.

**Comment by ZiggyAtl** [comment]
@paulstroot in the Purchase support note, it also needs to tell the user that the max characters is 200 with spaces. And that box isn't limited to 200 with spaces, which it should be. Also is it an easy one for you to make the explanation text, that appears in the box, greyed out and disappear when the user starts typing in the box? Just thinking about making it as user/idiot friendly as possible
