### ISSUE TITLE
text size

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-application#98]
Is it a quick job to chance the size of the text in the menu at the bottom of the website please? For consistency I think the menu items should be reduced to the same font size as the menu items at the top.

**Comment by paulstroot** [comment]
Yes. I can make that update.

@jennyvanderheiden copying you for visibility since it's a design change. This is where the update can be viewed before pushing to the live site.
https://comission-shopify-hydrogen-isj7f8lfy-ocupop.vercel.app/
